apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-rag
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-rag
  template:
    metadata:
      labels:
        app: postgres-rag
    spec:
      containers:
        - name: postgres-rag
          image: docker.io/muskanpatel71198/postgres-rag:12 
          imagePullPolicy: Always
          ports:
            - containerPort: 8501
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "1Gi"