apiVersion: v1
kind: Service
metadata:
  name: postgres-rag
  namespace: monitoring
spec:
  selector:
    app: postgres-rag
  ports:
    - protocol: TCP
      port: 8501
      targetPort: 8501
  type: NodePort